#version: '3'
#services:
#  app:
#    image: openai_proxy
#    ports:
#      - "8080:8080"
#    depends_on:
#      - redis
#    environment:
#      SPRING_REDIS_HOST: redis
#      SPRING_REDIS_PORT: 6379
#  redis:
#    image: redis
#    ports:
#      - "6379:6379"
version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      SPRING_REDIS_HOST: redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
